send_notification:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: hubble
    title:
      required: true
      selector:
        text: {}
    message:
      required: true
      selector:
        text:
          multiline: true
    level:
      selector:
        select:
          translation_key: notification_level
          options:
            - info
            - warning
            - error
            - critical
    permanent:
      selector:
        boolean: {}
    timer:
      selector:
        number:
          min: 1
          mode: box
    image:
      selector:
        text: {}

dismiss_notification:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: hubble
    notification_id:
      required: true
      selector:
        text: {}

start_timer:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: hubble
          domain: sensor
          device_class: enum
    duration:
      selector:
        number:
          min: 1
          mode: box
    label:
      selector:
        text: {}

pause_timer:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: hubble
          domain: sensor
          device_class: enum

resume_timer:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: hubble
          domain: sensor
          device_class: enum

reset_timer:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: hubble
          domain: sensor
          device_class: enum
